guitarscales/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('pages.urls')),
    url(r'^scales/', include('scales.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.conf.urls import url
from pages.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

scales/urls.py
from django.conf.urls import url
from scales.views import ScaleDetail

urlpatterns = [
    url(r'^(?P<slug>[-\w\d]+)/$', ScaleDetail.as_view(), name='scale-detail'),
]

pages/models.py
from django.db import models

# Create your models here.

scales/models.py
from django.db import models
from django.utils.text import slugify

class Scale(models.Model):
    key = models.CharField(max_length=2)
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify("{0}-{1}".format(self.key, self.name))
        if not(Scale.objects.filter(slug=self.slug)):
            super(Scale, self).save(*args, **kwargs)

    def __str__(self):
        return u"%s %s" % (self.key, self.name)

class Shape(models.Model):
    number = models.IntegerField()
    first_fret = models.IntegerField()
    scale = models.ForeignKey(Scale)

    def to_table(self):
        table = [[None for x in range(16)] for x in range(6)]

        for position in self.position_set.all():
            table[position.string - 1][position.fret - 1] = position

        return table


    def __str__(self):
        return u"%s %s" % (str(self.scale), self.number)

class Position(models.Model):
    fret = models.IntegerField()
    string = models.IntegerField()
    finger = models.IntegerField()
    is_root = models.BooleanField()
    shape = models.ForeignKey(Shape)

    def get_css_class(self):
        if self.is_root:
            return 'root'

        return 'note'

    def __str__(self):
        return u"%s Position: %d : %d" % (str(self.shape),
            self.fret, self.string)

    class Meta:
        ordering = ["string","fret"]

pages/views.py
from django.views.generic import TemplateView
from scales.models import Scale


class IndexView(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context["scales"] = Scale.objects.all()
        return self.render_to_response(context)

scales/views.py
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from scales.models import Scale


class ScaleDetail(DetailView):
    model = Scale
    template_name = 'scales/detail.html'

    def get_object(self):
        return get_object_or_404(Scale, slug=self.kwargs.get('slug', None))

pages/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <title>{{ scale.key }} {{ scale.name }}</title>
  </head>
  <body>
    <h1>Choose a scale:</h1>
    <select name="scale-id" id="scale-id" value="Select">
      <option disabled="disabled" selected>Select scale</option>
      {% for scale in scales %}
        <option value="{{ scale.slug }}">
          {{ scale }}
        </option>
      {% endfor %}
    </select>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $("#scale-id").on("change", function(){
          window.location.href = "/scales/" + $(this).val();
        });
    </script>
  </body>
</html>

scales/templates/scales/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <title>{{ scale.key }} {{ scale.name }}</title>
  </head>
  <body>
    <h1>{{ scale.key }} {{ scale.name }}</h1>
        {% for shape in scale.shape_set.all %}
        <p>Shape {{ shape.number }}</p>
        <table>
          <tbody>
          {% for string in shape.to_table %}
            <tr>
            {% for fret in string %}
              <td>
              {% if fret %}
                <div class="{{ fret.get_css_class }}">{{ fret.finger }}</div>
              {% endif %}
              </td>
            {% endfor %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% endfor %}
  </body>
</html>